project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "Xiaxin Joey Tang, Jiyan William Wang, and Yuan Ji"
    right: "MUSA 550 | Fall 2024 | University of Pennsylvania"

  sidebar:
    logo: "images/cover-icon.png"
    pinned: true
    align: center
    tools:
      - icon: backpack
        href: https://musa-550-fall-2024.github.io/course/
        text: "Class Website"
      - icon: github
        href: https://github.com/Xiaxin-Tang/final
        text: "Our GitHub"
      - icon: mortarboard
        href: https://www.design.upenn.edu/
        text: "Stuart Weitzman School of Design"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: about2.qmd
        text: Team
      - href: intro.qmd
        text: Introduction
      - section: analysis/index.qmd
        text: Analysis
        contents:
          - analysis/1-network.ipynb 
          - analysis/2-prediction.ipynb
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
