project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "Joey Xiaxin Tang, William Jiyan Wang, and Yuan Ji"
    right: "MUSA 550 | Fall 2024 | University of Pennsylvania"

  sidebar:
    logo: "images/Untitled-1.png"
    pinned: true
    align: center
    tools:
      - icon: home
        href: https://musa-550-fall-2024.github.io/course/
        text: "Class Website"
      - icon: github
        href: https://github.com/Xiaxin-Tang/final
        text: "Our GitHub"
      - icon: globe
        href: https://www.design.upenn.edu/
        text: "Stuart Weitzman School of Design"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: about.qmd
        text: About us
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
